//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace M2cToolite.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class M2cConst {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal M2cConst() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("M2cToolite.Properties.M2cConst", typeof(M2cConst).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 \Mir200\!abuse.txt 的本地化字符串。
        /// </summary>
        public static string AbuseConfig {
            get {
                return ResourceManager.GetString("AbuseConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Mir200\Envir\AdminList.txt 的本地化字符串。
        /// </summary>
        public static string AdminList {
            get {
                return ResourceManager.GetString("AdminList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Mir200\Castle\0\AttackSabukWall.txt 的本地化字符串。
        /// </summary>
        public static string AttackSabukWall {
            get {
                return ResourceManager.GetString("AttackSabukWall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Mir200\Envir\Robot_def\AutoRunRobot.txt 的本地化字符串。
        /// </summary>
        public static string AutoRunRobot {
            get {
                return ResourceManager.GetString("AutoRunRobot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Mir200\Exps.ini 的本地化字符串。
        /// </summary>
        public static string ExpsConfig {
            get {
                return ResourceManager.GetString("ExpsConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Mir200\Envir\Boxs 的本地化字符串。
        /// </summary>
        public static string Folder_Boxs {
            get {
                return ResourceManager.GetString("Folder_Boxs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Mir200\Envir 的本地化字符串。
        /// </summary>
        public static string Folder_Envir {
            get {
                return ResourceManager.GetString("Folder_Envir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Mir200\GuildBase 的本地化字符串。
        /// </summary>
        public static string Folder_GuildBase {
            get {
                return ResourceManager.GetString("Folder_GuildBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Mir200\Map 的本地化字符串。
        /// </summary>
        public static string Folder_Map {
            get {
                return ResourceManager.GetString("Folder_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Mir200\Envir\Market_Def 的本地化字符串。
        /// </summary>
        public static string Folder_MarketDef {
            get {
                return ResourceManager.GetString("Folder_MarketDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Mir200\Envir\MonItems 的本地化字符串。
        /// </summary>
        public static string Folder_MonItems {
            get {
                return ResourceManager.GetString("Folder_MonItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Mir200\Envir\MonUseItems 的本地化字符串。
        /// </summary>
        public static string Folder_MonUseItems {
            get {
                return ResourceManager.GetString("Folder_MonUseItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Mir200\Notice 的本地化字符串。
        /// </summary>
        public static string Folder_Notice {
            get {
                return ResourceManager.GetString("Folder_Notice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Mir200\Envir\Npc_Def 的本地化字符串。
        /// </summary>
        public static string Folder_NpcDef {
            get {
                return ResourceManager.GetString("Folder_NpcDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Mir200\Envir\QuestDiary 的本地化字符串。
        /// </summary>
        public static string Folder_QuestDiary {
            get {
                return ResourceManager.GetString("Folder_QuestDiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Mir200\Envir\UserData 的本地化字符串。
        /// </summary>
        public static string Folder_UserData {
            get {
                return ResourceManager.GetString("Folder_UserData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Mir200\Command.ini 的本地化字符串。
        /// </summary>
        public static string GameCommand {
            get {
                return ResourceManager.GetString("GameCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Mir200\GlobalVal.ini 的本地化字符串。
        /// </summary>
        public static string GlobalVal {
            get {
                return ResourceManager.GetString("GlobalVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Mir200\Envir\GuardList.txt 的本地化字符串。
        /// </summary>
        public static string GuardList {
            get {
                return ResourceManager.GetString("GuardList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Mir200\Envir\MapDesc.txt 的本地化字符串。
        /// </summary>
        public static string MapDesc {
            get {
                return ResourceManager.GetString("MapDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Mir200\Envir\MapEvent.txt 的本地化字符串。
        /// </summary>
        public static string MapEvent {
            get {
                return ResourceManager.GetString("MapEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Mir200\Envir\Mapinfo.txt 的本地化字符串。
        /// </summary>
        public static string Mapinfo {
            get {
                return ResourceManager.GetString("Mapinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Mir200\Envir\UserData\MapMagicEvent.txt 的本地化字符串。
        /// </summary>
        public static string MapMagicEvent {
            get {
                return ResourceManager.GetString("MapMagicEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Mir200\Envir\MapQuest.txt 的本地化字符串。
        /// </summary>
        public static string MapQuest {
            get {
                return ResourceManager.GetString("MapQuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Mir200\Envir\MerChant.txt 的本地化字符串。
        /// </summary>
        public static string MerChant {
            get {
                return ResourceManager.GetString("MerChant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Mir200\Envir\MiniMap.txt 的本地化字符串。
        /// </summary>
        public static string MiniMap {
            get {
                return ResourceManager.GetString("MiniMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Mir200\Envir\MonDropLimitList.txt 的本地化字符串。
        /// </summary>
        public static string MonDropLimitList {
            get {
                return ResourceManager.GetString("MonDropLimitList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Mir200\Envir\MonGen.txt 的本地化字符串。
        /// </summary>
        public static string MonGen {
            get {
                return ResourceManager.GetString("MonGen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Mir200\Envir\MonSayMsg.txt 的本地化字符串。
        /// </summary>
        public static string MonSayMsg {
            get {
                return ResourceManager.GetString("MonSayMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Mir200\Envir\NoClearMonList.txt 的本地化字符串。
        /// </summary>
        public static string NoClearMonList {
            get {
                return ResourceManager.GetString("NoClearMonList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Mir200\Envir\Npcs.txt 的本地化字符串。
        /// </summary>
        public static string NpcsConfig {
            get {
                return ResourceManager.GetString("NpcsConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Mir200\Envir\Market_Def\QFunction-0.txt 的本地化字符串。
        /// </summary>
        public static string QFunction {
            get {
                return ResourceManager.GetString("QFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Mir200\Envir\MapQuest_Def\QManage.txt 的本地化字符串。
        /// </summary>
        public static string QManage {
            get {
                return ResourceManager.GetString("QManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Mir200\Envir\Market_Def\QMission-0.txt 的本地化字符串。
        /// </summary>
        public static string Qmission {
            get {
                return ResourceManager.GetString("Qmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Mir200\Envir\Robot_def\RobotManage.txt 的本地化字符串。
        /// </summary>
        public static string RobotManage {
            get {
                return ResourceManager.GetString("RobotManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Mir200\Castle\0\SabukW.txt 的本地化字符串。
        /// </summary>
        public static string SabukWConfig {
            get {
                return ResourceManager.GetString("SabukWConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Mir200\!Setup.txt 的本地化字符串。
        /// </summary>
        public static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Mir200\Envir\StartPoint.txt 的本地化字符串。
        /// </summary>
        public static string StartPoint {
            get {
                return ResourceManager.GetString("StartPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Mir200\String.ini 的本地化字符串。
        /// </summary>
        public static string StringFiles {
            get {
                return ResourceManager.GetString("StringFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Mir200\Envir\UnbindList.txt 的本地化字符串。
        /// </summary>
        public static string UnbindList {
            get {
                return ResourceManager.GetString("UnbindList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Mir200\Envir\UserCmd.txt 的本地化字符串。
        /// </summary>
        public static string UserCmd {
            get {
                return ResourceManager.GetString("UserCmd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \Mir200\UserCmd.txt 的本地化字符串。
        /// </summary>
        public static string UserCmdEngine {
            get {
                return ResourceManager.GetString("UserCmdEngine", resourceCulture);
            }
        }
    }
}
